config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  
  enum document_pass: { selection1:0,not_pass1:1,pass1:2}
  enum interview_pass: { selection_before2:0,selection2:1,not_pass2:2,pass2:3}
  enum unofficial_offer: { selection_before3:0,selection3:1,not_pass3:2,pass3:3}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
  end

  def create
    job = Job.new(job_params)
    job.save
    redirect_to jobs_path
  end

  def index
    @job = Job.new
    @jobs = Job.all

    # 書類選考中
    @jobs1_0 = Job.where(document_pass: "0")
    # 書類落選
    @jobs1_1 = Job.where(document_pass: "1")
    # 書類通過
    @jobs1_2 = Job.where(document_pass: "2")

    # 面接ー
    @jobs2_0 = Job.where(interview_pass: "0")
    # 面接選考中
    @jobs2_1 = Job.where(interview_pass: "1")
    # 面接落選
    @jobs2_2 = Job.where(interview_pass: "2")
    # 面接通過
    @jobs2_3 = Job.where(interview_pass: "3")


    # 内定ー
    @jobs3_0 = Job.where(unofficial_offer: "0")
    # 内定選考中
    @jobs3_1 = Job.where(unofficial_offer: "1")
    # 内定落選
    @jobs3_2 = Job.where(unofficial_offer: "2")
    # 内定
    @jobs3_3 = Job.where(unofficial_offer: "3")
  end

  def show
  end

  def edit
    @job=Job.find(params[:id])
  end

  def update
    job=Job.find(params[:id])
    job.update(job_params)
    redirect_to jobs_path
  end

  def destroy
    job=Job.find(params[:id])
    job.destroy
    redirect_to jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:company_name,:document_pass,:interview_pass,:unofficial_offer)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<%= form_with model: @job do |f|%>
  <%= f.label :company_name, "会社名"%>
  <%= f.text_field :company_name %><br>
  <%= f.label :document_pass, "書類選考"%>
  <%= f.select :document_pass, Job.document_passes.keys.map{|k| [I18n.t("enums.job.document_pass.#{k}"),k]} %><br>
  <%= f.label :interview_pass, "面接選考"%>
  <%= f.select :interview_pass, Job.interview_passes.keys.map{|k| [I18n.t("enums.job.interview_pass.#{k}"),k]} %><br>
  <%= f.label :unofficial_offer, "内　　定"%>
  <%= f.select :unofficial_offer, Job.unofficial_offers.keys.map{|k| [I18n.t("enums.job.unofficial_offer.#{k}"),k]} %><br>
  <%= f.submit%>
<%end%>

app/views/jobs/index.html.erb
<div class="d-flex justify-content-center">
  <h1 class="mb-5 mt-4"><strong>転職活動実績</strong></h1>
</div>
<div class="d-flex justify-content-center">
  <div class="my_chart1">
    <canvas id="myChart1" width="300" height="300"></canvas>
    <p>書類選考<br><span>全<%= @jobs1_0.count+@jobs1_1.count+@jobs1_2.count%>件</span></p>
  </div>
  <div class="my_chart2 mx-5">
    <canvas id="myChart2" width="300" height="300"></canvas>
    <p>面接選考<br><span>全<%= @jobs2_1.count+@jobs2_2.count+@jobs2_3.count%>件</span></p>
  </div>
  <div class="my_chart3 mb-5">
    <canvas id="myChart3" width="300" height="300"></canvas>
    <p>内定<br><span>全<%= @jobs3_1.count+@jobs3_2.count+@jobs3_3.count%>件</span></p>
  </div>
</div>


<script>
window.onload = function () {
  var ctx = document.getElementById("myChart1");
  var myChart1 = new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: ['通過','選考中','落選'],
      datasets: [{
        backgroundColor: ['#3b82c4','#dbedf0','#dddddd'],
        data: [<%= @jobs1_2.count%>,<%= @jobs1_0.count%>,<%= @jobs1_1.count%>],
      }]
    },
    options: {
      responsive: false,
    }
  });

  var ctx = document.getElementById("myChart2");
  var myChart2 = new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: ['通過','選考中','落選'],
      datasets: [{
        backgroundColor: ['#3b82c4','#dbedf0','#dddddd'],
        data: [<%= @jobs2_3.count%>,<%= @jobs2_1.count%>,<%= @jobs2_2.count%>],
      }]
    },
    options: {
      responsive: false,
    }
  });

  var ctx = document.getElementById("myChart3");
  var myChart3 = new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: ['内定','選考中','落選'],
      datasets: [{
        backgroundColor: ['#3b82c4','#dbedf0','#dddddd'],
        data: [<%= @jobs3_3.count%>,<%= @jobs3_1.count%>,<%= @jobs3_2.count%>],
      }]
    },
    options: {
      responsive: false,
    }
  });
}
</script>


<%= form_with model: @job do |f|%>
  <%= f.label :company_name, "会社名"%>
  <%= f.text_field :company_name %>
  <%= f.label :document_pass, "書類選考"%>
  <%= f.select :document_pass, Job.document_passes.keys.map{|k| [I18n.t("enums.job.document_pass.#{k}"),k]} %>
  <%= f.label :interview_pass, "面接選考"%>
  <%= f.select :interview_pass, Job.interview_passes.keys.map{|k| [I18n.t("enums.job.interview_pass.#{k}"),k]} %>
  <%= f.label :unofficial_offer, "内　　定"%>
  <%= f.select :unofficial_offer, Job.unofficial_offers.keys.map{|k| [I18n.t("enums.job.unofficial_offer.#{k}"),k]} %>
  <%= f.submit%>
<%end%>

  <table class="table table-bordered">
    <tr>
      <th>会社名</th>
      <th>書類選考</th>
      <th>面接選考</th>
      <th>内定</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
<% @jobs.each do |job|%>
    <tr>
      <td><%= job.company_name %></td>
      <td><%= job.document_pass_i18n %></td>
      <td><%= job.interview_pass_i18n %></td>
      <td><%= job.unofficial_offer_i18n %></td>
      <td><%= link_to "編集",edit_job_path(job)%></td>
      <td><%= link_to "削除",job_path(job),method: :delete,"data-confirm"=>"本当に削除しますか？"%></td>
    </tr>
<%end%>
  </table>

app/views/jobs/show.html.erb
<h1>Jobs#show</h1>
<p>Find me in app/views/jobs/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Javascript</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>